CREATE DATABASE DEVISATE;

USE DEVISATE;

CREATE TABLE alunos(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL, 
	senha VARCHAR(255) NOT NULL,
	telefone VARCHAR(255) NOT NULL,
	sexo ENUM('M','F') NOT NULL DEFAULT 'F'
);